<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-5SV0R4LA" ignored="0" name="Command line test" tests="5" failures="1" timestamp="2022-05-22T11:22:56 CDT" time="30.095" errors="0">
  <testcase name="X" time="0.003" classname="scripts._01_AppleTest">
    <failure type="java.lang.AssertionError" message="Failure on purpose">
      <![CDATA[java.lang.AssertionError: Failure on purpose
at scripts._01_AppleTest.X(_01_AppleTest.java:55)
at java.util.ArrayList.forEach(ArrayList.java:1259)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- X -->
  <testcase name="testAppleTitle" time="1.015" classname="scripts._01_AppleTest"/>
  <testcase name="testAppleURL" time="1.474" classname="scripts._01_AppleTest"/>
  <testcase name="testAplicationFromHeading" time="0.718" classname="scripts._02_TechGlobalTest"/>
  <testcase name="testEtsyLogo" time="1.961" classname="scripts._03_EtsyTest"/>
</testsuite> <!-- Command line test -->
